ДЗ 1
BlackRule/2024-2-VK-EDU-Frontend-I-Chernovalov pull request #1
Opened 2024-09-25 00:50 UTC by BlackRule

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram или @kgrechin проверить его.
PS: В git config'е у меня стоит username/email Your Name <you@example.com> если это проблема - скажите....

2024-09-25 01:54 UTC, BlackRule commented
Остальных двоих добавлю сюда в reviewers  и assignees когда они примут collaborator invite

2024-09-25 21:09 UTC, martinkomitsky commented
> # Домашнее задание №1
> Прошу @martinkomitsky, @HaseProgram или @kgrechin проверить его. PS: В git config'е у меня стоит username/email Your Name [you@example.com](mailto:you@example.com) если это проблема - скажите....

Привет! да, очень нужно это исправить 
<img width="388" alt="image" src="https://github.com/user-attachments/assets/4574ae59-c8f0-47c4-b881-c87b404175df">

2024-09-25 22:34 UTC, BlackRule commented
исправил

2024-09-26 05:52 UTC, kgrechin requested changes

2024-09-26 05:52 UTC, kgrechin commented on hw1/convertBytesToHuman.js
> +  if (bytes < 0 || bytes === Infinity) return false;
объединить все ифы с return false в один
неочевидная проверка на NaN, лучше использовать isNan, тк тут есть еще проверка на Infinity, можно заменить на Number.isFinite

личное пожелание, делай пожалуйста отступы между логическими блоками в коде, когда строка за строкой,  тяжелее читать

2024-09-26 05:52 UTC, kgrechin commented on hw1/convertBytesToHuman.test.js
> +  // so BigInt needs to be handled?
если хочешь, можешь добавить)

2024-09-26 05:52 UTC, kgrechin commented on hw1/correctSentence.js
> +export default function correctSentence(text) {
добавить проверку входного параметра

2024-09-26 05:52 UTC, kgrechin commented on hw1/nonUniqueElements.js
> +    if (counts.get(el) > 1) result.push(el)
ставь пожалуйста в for скобки, с ифами еще ок, но с for не надо)

2024-09-26 05:52 UTC, kgrechin commented on hw1/nonUniqueElements.js
> +  const counts = new Map()
добавить проверку входного параметра

цикл с set(el, 0) - лишний, можно совместить со следующим

2024-09-27 09:23 UTC, kgrechin commented
@BlackRule, жду фиксов)

2024-09-27 13:37 UTC, BlackRule commented on hw1/correctSentence.js
> +export default function correctSentence(text) {
Этого не было в задании, но как скажете...

2024-09-27 13:43 UTC, BlackRule commented on hw1/nonUniqueElements.js
> +  const counts = new Map()
"добавить проверку входного параметра" не было в задании, но как скажете...

2024-09-27 13:46 UTC, BlackRule commented on hw1/nonUniqueElements.js
> +  const counts = new Map()
"цикл с set(el, 0) - лишний, можно совместить со следующим" нет

2024-09-27 13:57 UTC, BlackRule commented on hw1/convertBytesToHuman.test.js
> +  // so BigInt needs to be handled?
я передумал если что Это на будущее Тем кому делать будет нечего если бы это был реальный проект

2024-09-27 16:38 UTC, BlackRule commented
@kgrechin а я должен писать сюда типа "закончил" или это и так понятно?

2024-09-29 09:59 UTC, kgrechin commented on hw1/correctSentence.js
> +export default function correctSentence(text) {
можем давать доп задания от себя

2024-09-29 10:01 UTC, kgrechin commented on hw1/nonUniqueElements.js
> +  const counts = new Map()
да, можно объеденить, делая проверку если нет элемента то ставить 0 или 1 сразу иначе ++. зачем лишний проход делать

2024-09-29 10:03 UTC, kgrechin commented
@BlackRule, можешь не отписывать что закончил) плюс не надо самому резолвить комменты, это делают преподаватели и менторы. также если решил использовать исключения, то добавь на них тесты.

2024-09-29 14:07 UTC, BlackRule commented on hw1/nonUniqueElements.js
> +  const counts = new Map()
Как есть и по производительности оптимальнее и неужели добавление if'а не усложняет и людям чтение? и главное уровень сдвига вправо увеличивает... Было сказано "можно" а не "нужно" так что я считаю что как есть идеально. Если "нужно" то "объединю" Нужно?

2024-09-29 14:12 UTC, BlackRule commented
> @BlackRule, также если решил использовать исключения, то добавь на них тесты.
А как "добавить проверку входного параметра" если не бросанием Error'ов? Всё больше и больше добавляется требований которых изначально не было...

2024-09-30 02:57 UTC, kgrechin approved these changes
@HaseProgram, @martinkomitsky

2024-09-30 07:09 UTC, merged

2024-09-30 07:10 UTC, martinkomitsky commented
12!