hw2
BlackRule/2024-2-VK-EDU-Frontend-I-Chernovalov pull request #2
Opened 2024-10-01 15:44 UTC by BlackRule

# Домашнее задание №2

Прошу @martinkomitsky, @haseprogram или @kgrechin проверить его.

2024-10-02 05:43 UTC, kgrechin requested changes

2024-10-02 05:43 UTC, kgrechin commented on hw2/src/index.js
> +    <div class="text">${message.text}</div>
сюда сейчас можно вставить любую верстку через input, она должна превращаться в текст

2024-10-02 05:43 UTC, kgrechin commented on hw2/src/index.js
> +import './index.css';
@BlackRule 

нужно внести некоторые изменения:

сообщения должны быть прибиты книзу
пустые сообщения невозможно отправлять
сообщения собеседника слева, свои сообщения справа, на макете это есть

верстка не подстраивается, на лекции преподаватели говорили, что делаем responsive верстку
<img width="396" alt="Снимок экрана 2024-10-02 в 08 34 25" src="https://github.com/user-attachments/assets/76ffedcb-9ff8-406f-9684-164f5bbd0eee">

пожелания:

с localStorage работать только при первом лоаде для загрузки сообщений и при анлоаде для выгрузки
в реальном времени работать с локальным стейтом

2024-10-02 05:43 UTC, kgrechin commented on hw2/src/index.js
> +import './index.css';
input выглядит потерянным, добавить ему немного высоты, кнопку отправить и возможность "grow" вверх. сейчас все сообщение в одну строку вводится, что неудобно, нужно чтобы текст переносился и input "рос" вверх до какой-то определенной высоты.

2024-10-03 06:03 UTC, kgrechin requested changes

2024-10-03 06:03 UTC, kgrechin commented on hw2/src/index.js
> +    messages.innerHTML += `
escapeHTML хорошо, но лучше стараться вообще innerHTML не использовать, когда вставляются какие-то данные извне, а использовать innerText

2024-10-03 06:03 UTC, kgrechin commented on hw2/src/index.js
> +function autosize(textarea, row_limit) {
сейчас растет инпут, но теряется скролл в блоке сообщений, приходится  подскролливать книзу, нужно пофиксить

2024-10-03 06:55 UTC, BlackRule commented on hw2/src/index.js
> +    messages.innerHTML += `
но тогда придется DOM конструировать Всё равно будет React в котором JSX как innerHTML, поэтому так оставлю...
Значит готово и можно мне 12 баллов? :)

2024-10-03 08:01 UTC, kgrechin commented on hw2/src/index.js
> +    messages.innerHTML += `
следующее дз еще не с React. так что к следующему дз желательно пофиксить

2024-10-03 08:03 UTC, kgrechin approved these changes
@HaseProgram, @martinkomitsky, от меня аппрув

2024-10-03 09:30 UTC, HaseProgram approved these changes
12!

2024-10-03 09:31 UTC, merged