hw3
BlackRule/2024-2-VK-EDU-Frontend-I-Chernovalov pull request #3
Opened 2024-10-08 23:20 UTC by BlackRule

# Домашнее задание №3

Прошу @martinkomitsky, @haseprogram или @kgrechin проверить его.

2024-10-10 06:49 UTC, kgrechin requested changes

2024-10-10 06:49 UTC, kgrechin commented on hw2/src/components/chat.css
> +.chat{
@BlackRule 

<img width="1680" alt="Снимок экрана 2024-10-10 в 09 40 42" src="https://github.com/user-attachments/assets/19cddffe-08ba-4e43-9277-fbd748f75535">

нужно улучшить отображение многострочных сообщений, сейчас все в одну строку - не оч выглядит

основная задача дз - разбиение на компоненты (понятие принципа декомпозиции)
отпиши пожалуйста в текстовом виде сюда, как ты видишь декомпозицию страничек чатов и конкретного чата на компоненты и почему именно так)

2024-10-10 10:39 UTC, BlackRule commented on hw2/src/components/chat.css
> +.chat{
Если компонент будет обновляться то это должен быть отдельный компонент чтобы он не вызывал расчёт нужно ли перерендеривать его родителя а чтобы расчёт выполнялся только для него. Например бургер меню отдельный компонент если оно будет stateful а не сделано с помощью чекбокса. Так-же и чат в списке чатов это отдельный компонент так как перерендериваться будет отдельный чат. По той-же причине на экране чата список сообщений - это отдельный компонент (причем с функционалом recyclerview). Остальное по моему мнению нет необходимости бить на компоненты. Ну еще  выносить в компонент надо то что во многих местах повторяется.  Кнопка поиск для этого слишком мелкая а больше ничего такого не вижу. Ещё на компоненты можно бить  так чтобы покрыть тестами отдельный компонент.

2024-10-10 10:41 UTC, BlackRule commented on hw2/src/components/chat.css
> +.chat{
Ну, сообщение в списке сообщений на экране чата отдельный компонент если recyclerview того требует..

2024-10-10 11:55 UTC, BlackRule commented on hw2/src/components/chat.css
> +.chat{
Ну если считать что у topbar'а padding и bg-color везде один то можно вынести такой div из-за его особого стиля в компонент, хотя я бы просто в CSS сделал глобальный `.Topbar` класс и юзал бы `div.Topbar` а не создавал бы компонент.

2024-10-10 12:27 UTC, BlackRule commented
PS: страницу надо обновить со сбросом кэша почему-то.

2024-10-13 09:48 UTC, kgrechin approved these changes
<img width="1680" alt="Снимок экрана 2024-10-13 в 12 45 51" src="https://github.com/user-attachments/assets/12c8794c-2fc7-4cd4-8911-41fd0f189e09">

@BlackRule, на будущие дз сделать, чтобы сообщение растягивалось не на всю ширину экрана, а на какой-то процент, выглядит не оч прикольно, возможно подумать об обертке с ограничением max-width на какую-то ширину для всего блока, чтобы выглядело получше

@HaseProgram, @martinkomitsky от меня аппрув

2024-10-13 17:30 UTC, HaseProgram approved these changes
Класс, 12!

2024-10-13 17:31 UTC, merged