hw5
BlackRule/2024-2-VK-EDU-Frontend-I-Chernovalov pull request #5
Opened 2024-10-22 22:48 UTC by BlackRule

# Домашнее задание №5

Прошу @martinkomitsky, @haseprogram или @kgrechin проверить его.

2024-10-23 19:04 UTC, BlackRule commented
@kgrechin или кто-нибудь помогите пожалуйста. Я так много времени и главное нервов потратил на чтобы сделать "нормальную" прокрутку сообщений при resize'е textarea. Будто я инженер apple) Но В Firefox  например вот.  да и в других браузерах периодически проскакивает ненормальность

https://github.com/user-attachments/assets/9ba30acd-97f0-4f43-9734-9b0b731801d8

2024-10-26 07:11 UTC, kgrechin requested changes
@BlackRule, подлил фикс по textaarea

Отписал пару комментов,  которые нежно пофиксить

Также нужно настроить структуру проекта, пока что компонентов:

Давай разграничим компоненты на тупые и с логикой, допусти папка components -  папка с тупыми компонентами, без логики работы со сторами, LS, апи и тд:

components/Button
components/Header
components/Form
components/Textarea
...

Папка modules - папка с компонентами с логикой: 
modules/chat/ChatItem.jsx, ChatList.jsx...
modules/message/MessageItem.jsx, MessageList.jsx...

2024-10-26 07:11 UTC, kgrechin commented on react-chat/src/screens/chat/chat.jsx
> +function autosize(textarea, row_limit, onAfterResize = function (new_height) {
такое лучше уносить в utils, а не в компоненте хранить

2024-10-26 07:11 UTC, kgrechin commented on react-chat/src/screens/chat/chat.jsx
> +function Message({name,time,text,isNew}){
это отдельный компонент

2024-10-26 08:14 UTC, kgrechin commented
о ux/ui прикладываю пример, как можно оформить блоки, чтобы выглядело чуть покрасивше) при переключение на мобильное view - можно возвращать твою структуру оформления, без скруглений и отступов
тут тебе точно понадобятся стили: border-radius, margin, padding, box-shadow, background

можно поиграться с цветами, посмотреть какие-то готовые цветовые схемы на разных сайтах

также нужно поправить кнопку создания нового чата, так как она должна всегда быть в блоке сообщений и не вызодить за границы мессенджера.

<img width="641" alt="Снимок экрана 2024-10-26 в 11 14 43" src="https://github.com/user-attachments/assets/9d3d19c0-93b2-41a6-bdc4-0e7e3ae52cb4">

2024-10-26 08:20 UTC, kgrechin requested changes

2024-10-26 08:20 UTC, kgrechin commented on react-chat/src/screens/chat/chat.jsx
> +        autosizeFnThatNeedsCleanup.current=autosize(textarea, 10, () => {
можно унести в hook - useTextareaAutosize и там делать отписку от события, чтобы не призодилось писать в каждом компоненте

2024-10-26 08:20 UTC, kgrechin commented on react-chat/src/screens/chat/chat.jsx
> +
в react-way такое лучше не использовать, а ограничиваться useEffect с возвратом функции или componentWillUnmount в классовом компоненте

2024-10-27 12:57 UTC, BlackRule commented on react-chat/src/screens/chat/chat.jsx
> +
Но тогда ж не будет сохраняться при закрытии вкладки?

2024-10-31 05:47 UTC, kgrechin commented on react-chat/src/screens/chat/chat.jsx
> +
@BlackRule, ты прав,  для сохранения в ls надо будет использовать, лучше всего использовать события pagehide, visibilitychange, google также советует использовать их

https://developer.mozilla.org/ru/docs/Web/API/Window/pagehide_event

2024-11-06 10:56 UTC, BlackRule commented on react-chat/src/screens/chat/chat.jsx
> +function Message({name,time,text,isNew}){
https://youtu.be/u6MXyLght6I?t=1094
<img width="706" alt="image" src="https://github.com/user-attachments/assets/c9ebd414-4d01-41be-b320-17cf34b891bc"> Я всётаки думаю что если что-то используется лишь в одном месте пусть в том месте и будет

2024-11-06 10:57 UTC, BlackRule commented on react-chat/src/screens/chat/chat.jsx
> +function autosize(textarea, row_limit, onAfterResize = function (new_height) {
Я всётаки думаю что если что-то используется лишь в одном месте пусть в том месте и будет Я не знаю может на github нету но в IDE есть сворачивание кода же...

2024-11-06 11:19 UTC, kgrechin commented on react-chat/src/screens/chat/chat.jsx
> +function autosize(textarea, row_limit, onAfterResize = function (new_height) {
допустим будет заполнение профиля, в частности био, данных о юзере, там тоже можно использовать эту функцию для растущей текстареа, плюс как писал, ее можно сделать хуком. все, что может быть переиспользовано, лучше уносить в отдельные модули, а не хранить там где пригодилось

это скорее совет, решай сам

2024-11-06 11:21 UTC, kgrechin commented on react-chat/src/screens/chat/chat.jsx
> +function Message({name,time,text,isNew}){
не буду настаивать, но если нужно будет переиспользовать, то нужно будет выносить

2024-11-07 07:12 UTC, kgrechin commented
@BlackRule, по структуре будут фиксы?

2024-11-07 08:32 UTC, BlackRule commented
да. я как фиксану. щас фиксю. будет большой feature drop) и то что я хотел с прокруткой и ts и eslint и учёт замечаний в этом pr.  и hw6 позже сегодня

2024-11-08 15:36 UTC, BlackRule commented
@kgrechin `modules - папка с компонентами с логикой` пока нечего в неё положить тебе такие лежат в  screens. Да и врятли появится Разве что `App.tsx`... Или использующие `useKeepScrollPositionOnResize` `useAutosize` считаются "с логикой"?

2024-11-08 16:51 UTC, kgrechin commented
> @kgrechin `modules - папка с компонентами с логикой` пока нечего в неё положить тебе такие лежат в  screens. Да и врятли появится Разве что `App.tsx`... Или использующие `useKeepScrollPositionOnResize` `useAutosize` считаются "с логикой"?

@BlackRule, пока что оставь как есть, когда будет взаимодействие с беком, я отпишу что лучше куда вынести

2024-11-09 00:29 UTC, BlackRule commented
Я не понял почему 
![image](https://github.com/user-attachments/assets/7abc08b5-864d-4e1d-b45f-c9ee6536becd)
эти 2 первых из 3х коммитов что я щас запушил не оборажаются github'ом... Он только последний из запушенных комитов отображает? Тоесть их здесь в истории pull request'а вообще не упомянуто ну ладно... Я то их закоммитил ранее как видно а пушнул токо щас

2024-11-09 11:38 UTC, kgrechin approved these changes
@BlackRule, в прошлом дз прикладывал UI как можно улучшить блочки, чтобы выглядело чуть покрасивше, было бы прикольно если бы использовал

2024-11-09 11:40 UTC, kgrechin commented
12 баллов, комменты можно поправить уже в след дз

2024-11-09 11:40 UTC, merged