hw7
BlackRule/2024-2-VK-EDU-Frontend-I-Chernovalov pull request #7
Opened 2024-11-21 20:45 UTC by BlackRule

# Домашнее задание №7

Прошу @martinkomitsky, @haseprogram или @kgrechin проверить его.

Что было сделано:

2024-11-23 09:48 UTC, kgrechin reviewed
@BlackRule, 

- по заданию нужно - создать лс и групповой чат, создай лс чат со мной kgrechin
- пожалуйста убери все чувствительные данные
- добавь простейшую форму авторизации (я должен войти и написать тебе)
- проведи небольшой рефакторинг, типы в отдельные файлы, модульную логику в отдельные, что то мб в utils, постарайся избавиться от необходимости в eslint-disabled, весь закомментированные код, пометить как TODO: что-то сделать, либо удалить
- отображение даты у сообщений желательно привести к более читаемому виду
- добавить fallback на аватарку юзера и группового чата, если аватар не возвращается

2024-11-23 09:48 UTC, kgrechin commented on react-chat/IDEA http client/1register.http
> +
такого в репозитории точно не должно быть, нажно сделать хотябы простейшую форму авторизации:

два инпута на логин и пароль и прикрутить апи для авторизации, можно пока без авторизации

2024-11-23 09:48 UTC, kgrechin commented on react-chat/IDEA http client/2auth1_2024-11-12T132422.200.json
> +  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMTQxNzg2MSwiaWF0IjoxNzMxNDEwNjYxLCJqdGkiOiI2MjZhZmI4ZWUwYTc0ZjQ2YjkyNmE4MjAwZmZjODU5YSIsInVzZXJfaWQiOiJj
убрать все чувствительные данные

2024-11-23 09:48 UTC, kgrechin commented on react-chat/src/api.ts
> +const API_BASE = 'https://vkedu-fullstack-div2.ru/api'
все урлы лучше уносить в .env и в gh-secrets

2024-11-23 09:48 UTC, kgrechin commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
очень тяжело читаемо, плюс много eslint-disabled, в командной разработке такой код не зайдет

2024-11-23 09:48 UTC, kgrechin requested changes
@BlackRule

2024-11-23 12:07 UTC, BlackRule commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
Помогите с этим пожалуйста и возможно с react-chat/src/help me somebody please mentors.ts

2024-11-23 12:24 UTC, BlackRule commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
хотя с этим не надо. с указанием ts файлом можно но не обязательно

2024-11-23 12:27 UTC, BlackRule commented on react-chat/IDEA http client/2auth1_2024-11-12T132422.200.json
> +  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMTQxNzg2MSwiaWF0IjoxNzMxNDEwNjYxLCJqdGkiOiI2MjZhZmI4ZWUwYTc0ZjQ2YjkyNmE4MjAwZmZjODU5YSIsInVzZXJfaWQiOiJj
это тестовые аккаунты как вы знаете. это тестовые http client файлы IDEA. что тут чувствительного?. нет ни одного договора пароля к бд и тд

2024-11-23 12:36 UTC, kgrechin commented on react-chat/IDEA http client/2auth1_2024-11-12T132422.200.json
> +  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMTQxNzg2MSwiaWF0IjoxNzMxNDEwNjYxLCJqdGkiOiI2MjZhZmI4ZWUwYTc0ZjQ2YjkyNmE4MjAwZmZjODU5YSIsInVzZXJfaWQiOiJj
ты ходил в прод, зачем оставлять логины и пароли, access refresh токены в коде?

2024-11-23 12:38 UTC, kgrechin commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
не понял, с чем помочь? по еслинт можешь настроить конфиг как считаешь нужным

2024-11-23 12:40 UTC, kgrechin commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
по типам достаточно добавлять отступы между интерфейсами и типами, не делать комментов внутри типов, если они не сильно важны, плюс хранить типы не все в одной файле, а разносить на допустим users.types.ts messages.types.ts chats.types.ts, также и с клиентами для api иожно поступать

2024-11-23 14:03 UTC, BlackRule commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
там написано в /src/help me somebody please mentors.ts  Я хочу чтобы и внутри функции api ts понимал типы в зависимости от url. помогите если это возможно добиться этого. при этом чтоб как сейчас в api.ts сделано -в коде использующем api ts понимал типы. без as чтоб везде. автоматически ts форсил "раз url такой то data  и return type такой то"

2024-11-24 09:14 UTC, kgrechin commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
понял, завтра отпишу, пока фикси то, что отписал

2024-11-24 13:29 UTC, BlackRule commented on react-chat/IDEA http client/2auth1_2024-11-12T132422.200.json
> +  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMTQxNzg2MSwiaWF0IjoxNzMxNDEwNjYxLCJqdGkiOiI2MjZhZmI4ZWUwYTc0ZjQ2YjkyNmE4MjAwZmZjODU5YSIsInVzZXJfaWQiOiJj
Они не в коде За пределами папки src. логины и пароли от тестовых аккаунтов. Так что я удалять не буду ибо ничего секретного Просто демо данные и для тестов

2024-11-24 13:31 UTC, BlackRule commented on react-chat/IDEA http client/2auth1_2024-11-12T132422.200.json
> +  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMTQxNzg2MSwiaWF0IjoxNzMxNDEwNjYxLCJqdGkiOiI2MjZhZmI4ZWUwYTc0ZjQ2YjkyNmE4MjAwZmZjODU5YSIsInVzZXJfaWQiOiJj
Тем более что если бы я реально понял что это чувствительные данные то я знаю что их надо было бы удалять из всей истории GIT а это работа.  времени нет на полезную не то что на эту

2024-11-25 13:32 UTC, kgrechin commented on react-chat/IDEA http client/2auth1_2024-11-12T132422.200.json
> +  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMTQxNzg2MSwiaWF0IjoxNzMxNDEwNjYxLCJqdGkiOiI2MjZhZmI4ZWUwYTc0ZjQ2YjkyNmE4MjAwZmZjODU5YSIsInVzZXJfaWQiOiJj
добавь пожалуйста в gitignore

2024-11-25 13:32 UTC, kgrechin commented on react-chat/IDEA http client/2auth1_2024-11-12T132422.200.json
> +  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMTQxNzg2MSwiaWF0IjoxNzMxNDEwNjYxLCJqdGkiOiI2MjZhZmI4ZWUwYTc0ZjQ2YjkyNmE4MjAwZmZjODU5YSIsInVzZXJfaWQiOiJj
это не долго сделать

2024-11-25 14:06 UTC, kgrechin commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
тут свич/кейс сам не подхватит,  что если такой ключ то будем возвращать такой то тип, либо делать также map в виде объекта, либо указывать тип

```
type ApiInputMap = {
  'auth/POST': AuthPostInput;
  'user/GET': UserGetInput;
};

type ApiOutputMap = {
  'auth/POST': Auth;
  'user/GET': User;
};

const fetchUsers = () => {
  // как пример феча (здесь реальный феч должен быть)
  return <Promise<UserGetInput>>Promise.resolve({})
}

// вариант 1
async function api2<K extends keyof ApiInputMap>(
  url: K,
  data: ApiInputMap[K]
): ApiOutputMap[K] {
  switch (url) {
    case 'user/GET': {
      const result: ApiOutputMap['user/GET'] = await fetchUsers();
      return result;
    }
  }
}

// вариант 2
async function api2<K extends keyof ApiInputMap>(
  url: K,
  data: ApiInputMap[K]
): ApiOutputMap[K] {

  const handlers: ApiOutputMap = {
    'user/GET': async () => await fetchUsers(),
  }

  // с параметрами при запросе нужно будет добавить типы, тоже в мапу
  return handlers[url]();
}
```

2024-11-25 14:08 UTC, kgrechin commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
@BlackRule

2024-11-25 19:58 UTC, BlackRule commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
Спасибо!

2024-11-28 10:25 UTC, BlackRule commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
<img width="348" alt="image" src="https://github.com/user-attachments/assets/34fa99af-8e8b-40c1-af7c-2ab13a75e7f3">
Эх жалко мне всего потраченного на TS времени. Ну ладно пусть будет так как есть А то нарпимер | меня точно не устраивает. Хотя я и мог бы добавить типизацию return'ов
 TS почему-то не связывает в `function api<K extends keyof ApiInputMap>(
  url: K,
  data: ApiInputMap[K]
)`
аргументы ф-ии вместе url и data
И даже вот так почему-то я должен ему тыкать целых три(!) раза повторяя
<img width="422" alt="image" src="https://github.com/user-attachments/assets/c01c91f0-5387-4eee-9ea7-8801723d42ba">
Он даже так не понимает тип b на основании a
![image](https://github.com/user-attachments/assets/9be30f6f-9c93-4c4e-ab3a-18d87a517c2a)

2024-11-28 10:31 UTC, BlackRule commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
Хм https://stackoverflow.com/questions/57599715/tuple-where-a-succeeding-elements-type-is-dependent-on-the-value-of-a-preceding

2024-11-28 10:44 UTC, BlackRule commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
https://github.com/microsoft/TypeScript/issues/56920

2024-11-28 10:58 UTC, BlackRule commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
![image](https://github.com/user-attachments/assets/d7ed4ae6-6a59-47a0-b7a9-aa7fce5dd168)  
Какой то бестолковый язык ((

2024-11-28 11:03 UTC, BlackRule commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
И как избежать в  Unified Implementation повторения типов из Function With Multiple Signatures ИИ так и не смог даже если б TS'у было не пофиг Неясно тогда зачем вообще Function With Multiple Signatures если TS не может enforce return type depending on params type. 😡

2024-11-28 21:38 UTC, BlackRule commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
@kgrechin 
> типы в отдельные файлы, модульную логику в отдельные, что то мб в utils
  Я вещи связанные по **теме** держу в одном файле  если они не используются нигде кроме него.  Точнее я стараюсь чтобы всё было как можно меньше в том числе файлов
  Остальное сделал

2024-11-28 21:45 UTC, BlackRule commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
@kgrechin, Вы б заметили https://github.com/BlackRule/2024-2-VK-EDU-Frontend-I-Chernovalov/blob/0fbcf6fcca07b379937a99c559c84337eb0d1333/react-chat/src/screens/newGroupChat/NewGroupChat.tsx#L17 или хорошо что я указал?  Помогите пожалуйста.

2024-11-29 06:58 UTC, kgrechin commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
condition type должен выглядеть примерно так:

```
type ConditionType = {
  is_private: boolean;
} & (
  | { is_private: true; title: string }
  | { is_private: false; title?: string }
);
```

для handlersMap надо точно указать тип: ApiOutputMap

```
  const handlers: ApiOutputMap = {
    'user/GET': async () => await fetchUsers(),
  }
 ```
 
если возникают трудности с ts, которые тормозят разработку, то не надо его использовать, мы не обязуем писать на ts, будет отдельная лекция по ts, на которой вы узнаете про все принципы, а также получите задание, на небольшой рефакторинг проекта, с добавлением типов

пока что предлагаю сфокусироваться не на типах, а на общей логике и работе приложения, для этого чистого js без типизации хватит, в дальнейшем после лекции по typescript если будет желание и свободное время вы сможете перевести весь проект на него.

2024-11-29 06:59 UTC, kgrechin approved these changes
10 баллов

2024-11-29 06:59 UTC, merged

2024-12-01 12:04 UTC, BlackRule commented on react-chat/src/api.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
https://stackoverflow.com/questions/77324064/union-types-do-not-work-when-combined-with-omit
Вот в чем дело было Гениально "Omit doesn't distribute across unions; you need to make your own distributive version and use that instead"