Экзамен
BlackRule/2024-2-VK-EDU-Frontend-I-Chernovalov pull request #9
Opened 2024-12-23 18:09 UTC by BlackRule

Прошу @martinkomitsky или @haseprogram  проверить его.

2024-12-23 20:40 UTC, BlackRule commented
- [x] В корневой папке репозитория создать базовое приложение `exam` с помощью [CRA](https://github.com/facebook/create-react-app#quick-overview) (или vite) по инструкции выше
- [x] Сверстать 2 страницы и необходимые компоненты
- [x] Использовать стили. Дизайн должен быть похожим на макет
- [x] Реализовать перевод с одного языка на другой (нужно сделать так, чтобы можно было выбирать языки из выпадающего списка)
- [x] Реализовать перевод с неизвестного языка (автоопределитель из `API`)
- [x] Сохранять историю переводов в `localStorage`
- [x] Использовать `zustandt`
- [x] Использовать `React-router` для перехода между страницами
- [x] Задеплоить решение, используя `GitHub Actions`
- [ ] Ревью: получить правки по коду и исправить их (получаются лично у преподавателя и выполняются самостоятельно) [10 баллов]

2024-12-29 20:06 UTC, martinkomitsky commented on exam/src/App.tsx
> +
```suggestion
```

2024-12-29 20:09 UTC, martinkomitsky requested changes
Предварительная оценка: 36
По ревью вопросов нет.
Предлагаю выполнить фикс для последнего пункта:
* Нужно сделать так, чтобы подобная ситуация была невозможна
![image](https://github.com/user-attachments/assets/314c7df3-d9ac-4f47-865b-816347878ee7)

2025-01-10 11:51 UTC, martinkomitsky approved these changes

2025-01-10 11:51 UTC, merged